# frozen_string_literal: true

source "https://rubygems.org"

gem 'roda', '~> 3.52'
gem 'rack', '~> 2.2', '>= 2.2.3'
gem 'rack-unreloader', '~> 1.8'

group :development do
  gem 'pry'
  gem 'rubocop', require: false
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-roda'
end
